export const GENRE_MAP = {
  history: 'Исторический',
  horror: 'Ужасы',
  scifi: 'Фантастика',
  'stand-up': 'Стендап',
  fantasy: 'Фэнтези',
  drama: 'Драма',
  mystery: 'Детектив',
  family: 'Семейный',
  comedy: 'Комедия',
  romance: 'Мелодрама',
  music: 'Музыкальный',
  crime: 'Криминал',
  'tv-movie': 'Телефильм',
  documentary: 'Документальный',
  action: 'Боевик',
  thriller: 'Триллер',
  western: 'Вестерн',
  animation: 'Мультфильм',
  war: 'Военный',
  adventure: 'Приключения',
}
