export const GENRE_MAP = {
  history: 'исторический',
  horror: 'ужасы',
  scifi: 'фантастика',
  'stand-up': 'стендап',
  fantasy: 'фэнтези',
  drama: 'драма',
  mystery: 'детектив',
  family: 'семейный',
  comedy: 'комедия',
  romance: 'мелодрама',
  music: 'музыкальный',
  crime: 'криминал',
  'tv-movie': 'телефильм',
  documentary: 'документальный',
  action: 'боевик',
  thriller: 'триллер',
  western: 'вестерн',
  animation: 'мультфильм',
  war: 'военный',
  adventure: 'приключения',
}
